### ISSUE TITLE
How to use Rest API with your repo?

### ISSUE THREAD

**Issue by zydjohnHotmail** [KelvinVail/Betfair#2]
Hi,
I can see your repo is suitable to get data and send orders using stream.  But in some cases, I simply need REST client simple HTTP response, not the stream responses.
For example, what I want to do is like this:
First, I need to login using interactive method, I have my user name, password and API key, I need to get one session token to return.
Second, with the session token, I want to find the "Win" markets for greyhound races in both UK and in Ireland with the following information: market ID, race start time in GMT (actually not the real race begin time, but the time, racing staff can put the dogs in cages), the race course name with their country code; if possible I also want to get the dog names for 6 dogs for each race, which will take place within 24 hours.
Third, how can I logout, the Betfair API has a logout URL, you can use HTTP post request to send the login session token, which was received in the first step.
Then I finish all the job I want to know.
Since I want to list all greyhound races in 2 countries, which can be more than 100 races, but I don't need detailed data from any of the 100+ races/markets, so using stream is not necessary, I only need REST HTTP response.
Please advise or write some code samples to finish my job for the above 3 steps.
Thanks,

**Comment by KelvinVail** [comment]
Hi @zydjohnHotmail thank you for your question. And please except my apologies for not writing any documentation on how to use the Betfair API yet.

To log into the Betfair API. First create a Credentials object and then use it to create a BetfairApiClient.
```
var credentials = new Credentials("[USERNAME]", "[PASSWORD]", "[APP_KEY]");

using var client = new BetfairApiClient(credentials);
```
 
Before we can call the MarketCatalogue method on the BetfairApiClient. We need to create a "filter" to filter the markets that are returned, and a "query" to define what data is returned for each market..

```
var filter = new ApiMarketFilter()
    .WithMarketTypes(MarketType.Win)
    .WithCountries(Country.UnitedKingdom, Country.Ireland)
    .WithEventTypes(EventType.GreyhoundRacing)
    .FromMarketStart(DateTimeOffset.UtcNow)
    .ToMarketStart(DateTimeOffset.UtcNow.AddDays(1));

var query = new MarketCatalogueQuery()
    .Include(MarketProjection.Event)
    .Include(MarketProjection.MarketStartTime)
    .Include(MarketProjection.MarketDescription)
    .Include(MarketProjection.RunnerDescription);
```

Then call the MarketCatalogue method passing the filter and query.
```
var marketCatalogues = await client.MarketCatalogue(filter, query);
```

In the test I ran it returned 141 races okay. But if you request more than 200 records you will get a "TOO_MUCH_DATA" exception. If that occurs you will need to restrict the filter conditions and return the data you need using multiple requests. You can also limit the number of records returned using "Take" on the query. e.g.
```
var query = new MarketCatalogueQuery()
    .Include(MarketProjection.Event)
    .Include(MarketProjection.MarketStartTime)
    .Include(MarketProjection.MarketDescription)
    .Include(MarketProjection.RunnerDescription)
    .OrderBy(MarketSort.FirstToStart) // Order by closest to start time
    .Take(200); // Only take the first 200 markets
```

The query above will return the "MarketStartTime". I'm not familiar with greyhound racing so don't know if that is the same as the going down time you are looking for.

I have not added a function to explicitly log out. I will add that feature to my TODO list. Disposing the BetfairApiClient will also dispose the session token (but it will not log that token out and invalidate it).

Once again, thank you for your question. If I have missed anything or you have further questions please let me know.
